### ISSUE TITLE
SQLSTATE[HY000] [2002] No such file or directory on ExportData

### ISSUE THREAD

**Issue by pikonha** [fndomariano/trimania-crawler#5]
I'm trying to get data from every draw but I'm getting this error when I'm run the export command.

![image](https://user-images.githubusercontent.com/29408363/99071864-b578a380-2591-11eb-8528-3f71aacd3021.png)

**Comment by fndomariano** [comment]
Is there `data_csv` directory?

**Comment by pikonha** [comment]
Yeah, with only a .keep file in it.

**Comment by fndomariano** [comment]
I made a test here and it worked. Did you try to give permission on `data_csv` directory?

**Comment by pikonha** [comment]
This is what is inside my docker container 
![image](https://user-images.githubusercontent.com/29408363/99125638-3f049180-25e3-11eb-863d-5e55bbe8cf69.png)

Am I forgetting something?

**Comment by pikonha** [comment]
I haven't been able to do this work yet, I just want the site data. Would you mind sending me the numbers for each draw?

**Comment by fndomariano** [comment]
@picolloo if you wanna try again, get out from container, execute a `chmod 777` and `chown youruser:youruser`  on `data_csv` directory.

About the data, what period do you want?

**Comment by pikonha** [comment]
I got this, thank you.
